import { Copy, ExternalLink, LogOut, RefreshCw, ShieldCheck, WalletCards, Wifi, X } from 'lucide-react';
import { useSolanaWallet } from '../contexts/SolanaWalletContext';

export function shortenAddress(address: string | null) { return address ? `${address.slice(0, 4)}...${address.slice(-3)}` : ''; }

export function NetworkBadge({ wrong = false }: { wrong?: boolean }) { return <span className={`network-badge ${wrong ? 'wrong' : ''}`}><span />{wrong ? 'Wrong Network' : 'Solana Devnet'}</span>; }

export function WalletAddress({ address, copyable = false }: { address: string | null; copyable?: boolean }) { const { copyAddress } = useSolanaWallet(); if (!address) return <span className="wallet-address muted">Not connected</span>; return <span className="wallet-address">{shortenAddress(address)}{copyable && <button onClick={copyAddress} aria-label="Copy wallet address"><Copy size={12} /></button>}</span>; }

export function WalletBalance() { const { balance } = useSolanaWallet(); return <div className="wallet-balance"><span>Devnet balance</span><strong>{balance === null ? 'Balance unavailable' : `${balance.toFixed(2)} SOL`}</strong><small>DEVNET · test funds only</small></div>; }

export function SolanaWalletButton({ compact = false }: { compact?: boolean }) { const { connected, connecting, publicKey, network, connect, disconnect } = useSolanaWallet(); if (connected && network === 'devnet') return <button className={`wallet-connected ${compact ? 'compact' : ''}`} onClick={disconnect}><span className="wallet-status" /><span><strong>Wallet Connected</strong><WalletAddress address={publicKey} /></span><LogOut size={14} /></button>; return <button className={`wallet-connect-button ${compact ? 'compact' : ''}`} onClick={connect} disabled={connecting}><WalletCards size={15} />{connecting ? 'Connecting...' : 'Connect Solana Wallet'}</button>; }

export function WalletStatusPanel() { const { connected, publicKey, network, connect, disconnect, message, clearMessage } = useSolanaWallet(); return <div className="wallet-status-panel"><div className="wallet-panel-top"><div className="wallet-panel-icon"><ShieldCheck size={20} /></div><div><div className="eyebrow">Solana identity</div><h3>Wallet connection</h3></div><NetworkBadge wrong={network === 'wrong-network'} /></div>{connected && network === 'devnet' ? <><div className="wallet-identity-row"><div><span>Wallet</span><strong><WalletAddress address={publicKey} copyable /></strong></div><div><span>Network</span><strong>Solana Devnet</strong></div><div><span>Status</span><strong className="green-text">Connected ✓</strong></div></div><WalletBalance /><div className="wallet-panel-actions"><button className="button outline" onClick={disconnect}><LogOut size={14} /> Disconnect</button><a href="https://faucet.solana.com/" target="_blank" rel="noreferrer" className="text-link">Need Devnet SOL? <ExternalLink size={13} /></a></div></> : <div className="wallet-empty"><p>{network === 'wrong-network' ? 'Please switch your wallet to Solana Devnet to continue.' : 'Connect Phantom or another compatible Solana mobile wallet to associate a public address with your CropCred profile.'}</p><button className="button primary" onClick={connect}>{network === 'wrong-network' ? 'Switch to Solana Devnet' : 'Connect Wallet'}</button></div>}{message && <div className="wallet-message"><Wifi size={13} />{message}<button onClick={clearMessage} aria-label="Dismiss"><X size={13} /></button></div>}</div>; }
